<?php

return [
    'policy_version' => '2026-09-12-v1',
    'review_interval_days' => 365,
    'global_delete_after_days' => null,
    'legal_hold_overrides_retention' => true,
    'normal_application_role_may_purge' => false,

    'executor' => [
        'enabled' => env('RETENTION_EXECUTOR_ENABLED', false),
        'max_rows_per_execution' => (int) env('RETENTION_EXECUTOR_MAX_ROWS', 1000),
        'allowed_data_classes' => [
            'idempotency_records',
        ],
    ],

    'classes' => [
        'formal_training_register' => [
            'controller_scope' => 'tenant_osk_controller',
            'basis_kind' => 'statutory',
            'clock' => ['kind' => 'months_after_anchor', 'value' => 120],
            'anchor' => 'last_formal_register_entry_at',
            'disposition' => 'retain_minimal_formal_record_until_cutoff_then_erase_or_anonymize_where_no_other_basis',
            'source' => 'Dz.U. 2018 poz. 1885 par_18_ust_1_pkt_1',
            'legal_hold' => true,
        ],
        'lesson_card_detail' => [
            'controller_scope' => 'tenant_osk_controller',
            'basis_kind' => 'statutory',
            'clock' => ['kind' => 'months_after_anchor', 'value' => 24],
            'anchor' => 'last_lesson_card_entry_at',
            'disposition' => 'destroy_after_required_hours_summary_is_persisted',
            'source' => 'Dz.U. 2018 poz. 1885 par_18_ust_2_3',
            'legal_hold' => true,
        ],
        'internal_exam_result_summary' => [
            'controller_scope' => 'tenant_osk_controller',
            'basis_kind' => 'formal_training_evidence_policy',
            'clock' => ['kind' => 'inherit', 'from' => 'formal_training_register'],
            'anchor' => 'linked_course_formal_register_cutoff',
            'disposition' => 'retain_minimal_result_evidence_only',
            'legal_hold' => true,
        ],
        'internal_exam_detailed_attempt' => [
            'controller_scope' => 'tenant_osk_controller',
            'basis_kind' => 'purpose_based_product_policy',
            'clock' => ['kind' => 'months_after_anchor', 'value' => 24],
            'anchor' => 'attempt_terminal_at',
            'disposition' => 'erase_detailed_question_answer_snapshot_keep_required_summary',
            'legal_hold' => true,
        ],
        'student_contact_operational' => [
            'controller_scope' => 'tenant_osk_controller',
            'basis_kind' => 'purpose_based_product_policy',
            'clock' => ['kind' => 'days_after_anchor', 'value' => 30],
            'anchor' => 'all_operational_relationships_ended_at',
            'disposition' => 'erase_or_anonymize_contact_fields_unless_documented_basis_remains',
            'legal_hold' => true,
        ],
        'student_formal_identity' => [
            'controller_scope' => 'tenant_osk_controller',
            'basis_kind' => 'statutory_formal_record_support',
            'clock' => ['kind' => 'inherit', 'from' => 'formal_training_register'],
            'anchor' => 'latest_linked_formal_register_cutoff',
            'disposition' => 'retain_only_identity_fields_required_for_formal_record',
            'legal_hold' => true,
        ],
        'local_pkk_sensitive_identity' => [
            'controller_scope' => 'tenant_osk_controller',
            'basis_kind' => 'purpose_based_product_policy',
            'clock' => ['kind' => 'months_after_anchor', 'value' => 24],
            'anchor' => 'course_terminal_at',
            'disposition' => 'erase_full_ciphertext_and_lookup_hash_when_no_operational_or_legal_basis_remains',
            'legal_hold' => true,
        ],
        'finance_accounting_records' => [
            'controller_scope' => 'tenant_or_platform_controller_by_transaction',
            'basis_kind' => 'statutory_minimum',
            'clock' => ['kind' => 'fiscal_year_following_start_plus_years', 'value' => 5],
            'anchor' => 'fiscal_year_end',
            'disposition' => 'retain_financial_evidence_until_cutoff',
            'source' => 'ustawa_o_rachunkowosci_art_74',
            'legal_hold' => true,
        ],
        'audit_security_evidence' => [
            'controller_scope' => 'platform_and_tenant_as_applicable',
            'basis_kind' => 'purpose_based_security_claims_policy',
            'clock' => ['kind' => 'months_after_anchor', 'value' => 36],
            'anchor' => 'event_at',
            'disposition' => 'privileged_retention_only_no_normal_runtime_delete',
            'legal_hold' => true,
        ],
        'auth_sessions' => [
            'controller_scope' => 'platform_controller',
            'basis_kind' => 'security_product_policy',
            'clock' => ['kind' => 'days_after_anchor', 'value' => 90],
            'anchor' => 'revoked_or_expired_or_last_seen_terminal_at',
            'disposition' => 'purge_session_security_metadata',
            'legal_hold' => true,
        ],
        'activity_notifications' => [
            'controller_scope' => 'tenant_osk_controller',
            'basis_kind' => 'product_history_policy',
            'clock' => ['kind' => 'months_after_anchor', 'value' => 12],
            'anchor' => 'created_or_occurred_at',
            'disposition' => 'purge_projection_only_without_cascade_to_business_authority',
            'legal_hold' => true,
        ],
        'idempotency_records' => [
            'controller_scope' => 'technical_processor',
            'basis_kind' => 'technical_ttl',
            'clock' => ['kind' => 'days_after_anchor', 'value' => 30],
            'anchor' => 'completed_at',
            'disposition' => 'purge_after_expiry_and_only_safe_response_snapshot',
            'legal_hold' => false,
        ],
        'outbox_published' => [
            'controller_scope' => 'technical_processor',
            'basis_kind' => 'technical_ttl',
            'clock' => ['kind' => 'days_after_anchor', 'value' => 30],
            'anchor' => 'published_at',
            'disposition' => 'purge_only_published_terminal_rows_without_cascade',
            'legal_hold' => false,
            'automatic_conditions' => ['publication_state' => 'published'],
        ],
        'temporary_unattached_assets' => [
            'controller_scope' => 'technical_processor',
            'basis_kind' => 'technical_ttl',
            'clock' => ['kind' => 'days_after_anchor', 'value' => 7],
            'anchor' => 'created_at',
            'disposition' => 'delete_unattached_nonformal_asset_and_object',
            'legal_hold' => false,
        ],
        'application_logs' => [
            'controller_scope' => 'platform_controller',
            'basis_kind' => 'observability_policy',
            'clock' => ['kind' => 'days_after_anchor', 'value' => 30],
            'anchor' => 'log_event_at',
            'disposition' => 'delete_or_aggregate_without_direct_identifier',
            'legal_hold' => true,
        ],
        'security_logs' => [
            'controller_scope' => 'platform_controller',
            'basis_kind' => 'security_policy',
            'clock' => ['kind' => 'days_after_anchor', 'value' => 90],
            'anchor' => 'security_event_at',
            'disposition' => 'delete_after_security_window_unless_incident_hold',
            'legal_hold' => true,
        ],
        'provider_pkk_raw_payload' => [
            'controller_scope' => 'undetermined_until_provider_authority',
            'basis_kind' => 'deferred_external_authority',
            'clock' => ['kind' => 'deferred'],
            'anchor' => null,
            'disposition' => 'collection_forbidden_until_PWPW_provider_policy_is_verified',
            'legal_hold' => true,
        ],
    ],
];
